=== jinshihui88/study/后台学习资料/javaweb/示例代码/解析xml文件例子/xmlTest/test3.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[a-z]{3}">
				</xs:pattern>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="sex" type="sexType" />
	<xs:simpleType name="sexType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="male"></xs:enumeration>
			<xs:enumeration value="female"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="age" >
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1" />
				<xs:maxInclusive value="100" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="password" type="sexType">
	</xs:element>
	
	<xs:element name="student">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"></xs:element>
				<xs:element ref="age"></xs:element>
				<xs:element ref="sex"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="teacher">
		<xs:complexType>
			<!--  <xs:complexContent>
				<xs:extension base="sexType">
					<xs:sequence>
						<xs:element name="female" type="xs:string"></xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
			-->
			
			<xs:attribute name="kc" type="xs:string">
			</xs:attribute> 
		</xs:complexType>
	</xs:element>
	
	<xs:element name="students">		
		<xs:complexType >
			<xs:sequence >
				<xs:element ref="student" maxOccurs="unbounded" ></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jinshihui88/study/后台学习资料/javaweb/示例代码/解析xml文件例子/xmlTest/test3.xml
<?xml version="1.0" encoding="UTF-8" ?>

<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="test3.xsd">
	<student>
		<name>war</name>
		<age>18</age>
		<sex>male</sex>
	</student>
	
	<student >
		<name>fox</name>
		<age>18</age>
		<sex>female</sex>
	</student>
</students>
